# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cocoapod-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoapod-sample
  pod 'Alamofire', '~> 4.0'
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
  pod 'SwiftyJSON'
  pod 'PKHUD'

end
